
base:
  url: localhost
server:
  port: 8091
spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:pcatalog
    username: sa
    password: pass
    driverClassName: org.h2.Driver
