base:
  url: localhost
server:
  port: 8091
spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:pcatalog
    username: sa
    password: pass
    driverClassName: org.h2.Driver

integration:
  route:
    product:
      reserved: rabbitmq://localhost:5672/product-reserve?autoDelete=false&queue=product-reserve&username=reservation&password=reservation&routingKey=new-product-reservation
    user:
      newUserIn: rabbitmq://localhost:5672/register-client?autoDelete=false&queue=register-client&username=reservation&password=reservation&routingKey=new-client-register
